### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by ylwu111** [LucaslcFreitas/Zero-Trust#1]
i found that the database.sql has many unreadable codes, and i can't solve it by turn it into utf-8, can you give me some advice? thanks!!
![image](https://github.com/LucaslcFreitas/Zero-Trust/assets/149852121/aa2dbc9c-a40e-4c76-9066-cd011e06dc14)

**Comment by LucaslcFreitas** [comment]
Hi. This file was generated through a database backup in PostgreSQL, with the aim of easily restoring your data. Try creating a database named "zt-ehealth" and restoring the data from this file :)

**Comment by ylwu111** [comment]
Thank you！I have solved the problem and run it successfully. I'm just a new starter of Zero Trust, your project helps me a lot! :)
